apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx-ingress-controller
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
  selector:
    name: nginx-ingress-controller
