apiVersion: v1
kind: LimitRange
metadata:
  name: mylimits
spec:
  limits:
  - type: Pod
    min:
      cpu: 200m
      memory: 6Mi
    max:
      cpu: "2"
      memory: 1Gi
  - type: Container
    min:
      cpu: 100m
      memory: 3Mi
    max:
      cpu: "2"
      memory: 1Gi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    default:
      cpu: 300m
      memory: 200Mi