apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: daemonset-nginx
  labels:
    app: daemonset-nginx
spec:
  template:
    metadata:
      labels:
        name: daemonset-nginx
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - image: nginx:1.10-alpine
          name: daemonset-nginx
