apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    name: ghost
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 2368
      protocol: TCP
      nodePort: 30100
  selector:
    name: ghost
